---
- name: Pull dotfiles Periodically
  cron:
    name: 'pull dotfiles'
    minute: '0'
    job: 'cd ~/dotfiles && git reset --hard origin/master &> /dev/null && git clean -fxd &> /dev/null && git pull -q &> /dev/null'